services:
  nats:
    container_name: nats
    image: nats:2.10.25-alpine3.21
    ports: 
      - "4222:4222"
    restart: on-failure
    command:
      - '--jetstream'
      - '--store_dir=/var/lib/nats/data'
